schema_version: 1
streams:
  - id: execution_left_arm_joint_reference
    topic: /execution/left_arm/joint_reference
    expected_type: trajectory_msgs/msg/JointTrajectory
    required: true
    start_gate: false
    qos:
      mode: explicit
      reliability: reliable
      durability: volatile
      depth: 10

  - id: execution_left_gripper_joint_reference
    topic: /execution/left_gripper/joint_reference
    expected_type: trajectory_msgs/msg/JointTrajectory
    required: false
    start_gate: false
    qos:
      mode: explicit
      reliability: reliable
      durability: volatile
      depth: 10

  - id: execution_right_arm_joint_reference
    topic: /execution/right_arm/joint_reference
    expected_type: trajectory_msgs/msg/JointTrajectory
    required: true
    start_gate: false
    qos:
      mode: explicit
      reliability: reliable
      durability: volatile
      depth: 10

  - id: execution_right_gripper_joint_reference
    topic: /execution/right_gripper/joint_reference
    expected_type: trajectory_msgs/msg/JointTrajectory
    required: false
    start_gate: false
    qos:
      mode: explicit
      reliability: reliable
      durability: volatile
      depth: 10

  - id: robot_joint_states
    topic: /joint_states
    expected_type: sensor_msgs/msg/JointState
    required: true
    start_gate: true
    qos:
      mode: sensor_data

  # Cameras observation streams:
  - id: static_orbbec_color
    topic: /observation/static_orbbec/color/image_raw
    expected_type: sensor_msgs/msg/Image
    required: false
    start_gate: false
    qos:
      mode: sensor_data

  - id: left_wrist_realsense_color
    topic: /observation/left_hand_realsense/color/image_raw
    expected_type: sensor_msgs/msg/Image
    required: false
    start_gate: false
    qos:
      mode: sensor_data

  - id: right_wrist_realsense_color
    topic: /observation/right_hand_realsense/color/image_raw
    expected_type: sensor_msgs/msg/Image
    required: false
    start_gate: false
    qos:
      mode: sensor_data

