<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>manipulation_position_controllers</name>
  <version>0.3.1</version>
  <description>Generic ros2_control joint/task kinematic and joint-impedance controller plugins for manipulation.</description>

  <maintainer email="42087775+Gabriel-Ning@users.noreply.github.com">Ning Guo</maintainer>
  <license>Apache-2.0</license>

  <url type="website">https://github.com/Gabriel-Ning/phy_ai_runtime_controllers</url>
  <url type="repository">https://github.com/Gabriel-Ning/phy_ai_runtime_controllers.git</url>
  <url type="bugtracker">https://github.com/Gabriel-Ning/phy_ai_runtime_controllers/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>control_toolbox</depend>
  <depend>controller_interface</depend>
  <depend>diagnostic_msgs</depend>
  <depend>diagnostic_updater</depend>
  <depend>eigen</depend>
  <depend>geometry_msgs</depend>
  <depend>hardware_interface</depend>
  <depend>moveit_msgs</depend>
  <depend>osqp</depend>
  <depend>osqp-eigen</depend>
  <depend>pinocchio</depend>
  <depend>placo</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>realtime_tools</depend>
  <depend>ruckig</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>trajectory_msgs</depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>controller_manager</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>mock_components</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>robot_state_publisher</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
